[project]
name = "PhdAssess Meteor app"
revision = "1.0"

[profiles.default]

PHDASSESS_ENCRYPTION_KEY = { description = "The key to encrypt/decrypt values saved in Zeebe", required = true }

AUTH_ENTRA_TENANT_ID = { description = "The ID of the tenant the app will auth the users on Entra", required = true }
AUTH_ENTRA_CLIENT_ID = { description = "The ID of the client the app will auth the users on Entra", required = true }
AUTH_ENTRA_SECRET = { description = "The secret that assert the app is allowed to auth on Entra", required = true }

ALFRESCO_URL = { description = "The url where documents are downloaded/uploaded on Alfresco. Only needed if you want to deposit PDFs." }
ALFRESCO_USERNAME = { description = "The Alfresco username. Only needed if you want to deposit PDFs." }
ALFRESCO_PASSWORD = { description = "The Alfresco password. Only needed if you want to deposit PDFs." }

API_EPFL_CH_TOKEN = { description = "Token to connect to the person api to convert sciper to info", required = true  }
